package:
  name: jom
  version: 1.0.16

source:
  fn: jom_1_0_16.zip                                                 [win]
  url: http://download.qt.io/official_releases/jom/jom_1_0_16.zip    [win]

test:
  commands:
    - jom /H

about:
    home: http://www.swig.org/
    license: GPLv3

