package:
  name: pyxb
  version: "1.2.4"

source:
  fn: PyXB-1.2.4.tar.gz
  url: https://pypi.python.org/packages/source/P/PyXB/PyXB-1.2.4.tar.gz
  md5: cea2ffde4a36ca88f76c687ee6549cfd

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - pyxb
    - pyxb.binding
    - pyxb.bundles
    - pyxb.bundles.common
    - pyxb.bundles.common.raw
    - pyxb.bundles.dc
    - pyxb.bundles.dc.raw
    - pyxb.bundles.saml20
    - pyxb.bundles.saml20.raw
    - pyxb.bundles.wssplat
    - pyxb.bundles.wssplat.raw
    - pyxb.namespace
    - pyxb.utils
    - pyxb.xmlschema

about:
  home: http://pyxb.sourceforge.net
  license: Apache Software License
  summary: 'PyXB ("pixbee") is a pure Python package that generates Python source code for classes that correspond to data structures defined by XMLSchema.'
