package:
  name: cclib
  version: "1.3.1"

source:
  fn: cclib-1.3.1.tar.gz
  url: https://github.com/cclib/cclib/releases/download/v1.3.1/cclib-1.3.1.tar.gz
  md5: c86394f79834a729737295dc15ddbe72


requirements:
  build:
    - python

  run:
    - python
    - numpy

test:
  imports:
    - cclib
    - cclib.bridge
    - cclib.method
    - cclib.parser
    - cclib.progress

about:
  home: http://cclib.github.io/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'cclib: parsers and algorithms for computational chemistry'
