package:
  name: funcsigs
  version: "1.0.0"

source:
  fn: funcsigs-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/f/funcsigs/funcsigs-1.0.0.tar.gz
  md5: 669d0f34e94cb36a3948e8f592bc6f25
  patches:
    - ordereddict.patch

build:
  noarch_python: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - ordereddict # [py26]

  run:
    - python
    - ordereddict # [py26]

test:
  # Python imports
  imports:
    - funcsigs

about:
  home: http://funcsigs.readthedocs.org
  license: Apache Software License
  summary: 'Python function signatures from PEP362 for Python 2.6, 2.7 and 3.2+'

