package:
  name: parse
  version: !!str 1.6.6

source:
  fn: parse-1.6.6.tar.gz
  url: https://pypi.python.org/packages/source/p/parse/parse-1.6.6.tar.gz
  md5: 11bc8c60a30fe52db4ac9a827653d0ca

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - parse

about:
  home: https://github.com/r1chardj0n3s/parse
  license: BSD License
  summary: 'parse() is the opposite of format()'
