package:
  name: clusterutils
  version: 0.1.2

source:
   url: https://github.com/choderalab/clusterutils/archive/0.1.2.tar.gz
   fn: 0.1.2.tar.gz

build:
  entry_points:
    - build_mpirun_configfile = clusterutils.build_mpirun_configfile:main
  skip:
    - [not unix]
    
requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/choderalab/clusterutils
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Tools for use in compute cluster environments.
