package:
  name: hmmlearn
  version: "0.3.0b"

source:
  git_url: https://github.com/hmmlearn/hmmlearn.git
  git_tag: 86003c9999b2b36796198a918cf7c5258a56411c

build:
  # TODO: https://github.com/ContinuumIO/anaconda-issues/issues/557
  skip: True  # [win32 and py35 and np == 19]

requirements:
  build:
    - python
    - numpy x.x
    - cython
    - nose
    - scipy
    - scikit-learn
    - pytest

  run:
    - python
    - numpy x.x
    - scikit-learn

test:
  imports:
    - hmmlearn

about:
  home: https://github.com/hmmlearn/hmmlearn
  license: BSD
  summary: "Hidden Markov Models in Python with scikit-learn like API"
