os:
  - linux
  - osx

# Supported osx/xcode versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
# See also: https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/
osx_image: xcode6.4

language: c
sudo: required

services:
  - docker

env:
  global:
    - CONDA_BUILD: "2.0.1"
    - CUDA_VERSION: "7.5"
    - CUDA_SHORT_VERSION: "75"
  secure: 
    - "Bn7+i0qCzcm7XUWY9nMgB1L7KC5VCsJgsSMwSHlAOXs3HjVJerxTHQohq6OMafyPCfnzRyY4dca1Wl3uRA2eXLJTB8uCyAgWoT/oIepVeplyVeWLPkQzRoiCSDMTeFTZY9imgh/Qkap+6mZ34fXh/Q4XBxZ7jGrpooq2TUst9Ac="

install:
  # The Dockerfile that defines the image that for the build environment is
  # available in this repo at devtools/omnia-build-box/Dockerfile
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30;
    fi

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="--upload omnia";
    else
        export UPLOAD=" ";
    fi
  - echo $UPLOAD

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST -e CONDA_BUILD
            -t -i --rm -v `pwd`:/io jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "Building osx...";
        bash devtools/osx-build.sh;
    fi
