os:
  - linux
  - osx

# Supported osx/xcode versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
# See also: https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/
osx_image: xcode6.4

language: c
sudo: required

services:
  - docker

env:
  global:
    - CONDA_BUILD: "2.0.1"
    - CUDA_VERSION: "7.5"
    - CUDA_SHORT_VERSION: "75"
  secure:
    - "GjbAskNQDToMpTQ87p2TcG+JPdr+TIyWxarkzwd/KCQLuJqTKVVinWtKZwB+uaEnz2mmnXT7jFgbUU2Vuq0Dv78SOgTnqeh+ObP60imN4z8TB88PAFihv7JDJ45Nfbe7viKrWLWDYRebkObbJduc7xms0YEb9vs4e1+knTojiEc="
    # The Dockerfile that defines the image that for the build environment is
# available in this repo at devtools/centos5-build-box/Dockerfile
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30;
    fi

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="--upload omnia";
    else
        export UPLOAD=" ";
    fi
  - echo $UPLOAD

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST -e CONDA_BUILD
            -t -i --rm -v `pwd`:/io jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "Building osx...";
        bash devtools/osx-build.sh;
    fi
