package:
  name: sphinxcontrib-lunrsearch
  version: "0.2"

source:
  fn: 0.2.zip
  url: https://github.com/rmcgibbo/sphinxcontrib-lunrsearch/archive/0.2.zip

build:
  noarch_python: True

requirements:
  build:
    - setuptools
    - python
    - sphinx >=1.0
    - six >=1.4.1

  run:
    - python
    - sphinx >=1.0
    - six >=1.4.1

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.lunrsearch

about:
  home: https://github.com/rmcgibbo/sphinxcontrib-lunrsearch
  license: MIT License
  summary: 'Instant search for Sphinx'
