package:
  name: propertyestimator
  version: 0.0.1

source:
  git_url: https://github.com/openforcefield/propertyestimator.git
  git_tag: master

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]

extra:
  #force_upload: True
  upload: rc # Upload to anaconda with the "main" label.

requirements:
  build:

    # For building sphinx docs
    - sphinx
    - sphinx_bootstrap_theme
    - sphinx_rtd_theme
    - numpydoc
    - nbsphinx
    - m2r >=0.2.1
    - testpath ==0.3.1
    
    # Run deps must be installed to build sphinx docs
    - python
    - setuptools
    - openforcefield ==0.4.0
    - smirnoff99frosst
    - numpy
    - pandas
    - openmm
    - pint
    - packmol
    - pymbar
    - mdtraj
    - dask
    - distributed >=2.1
    - dask-jobqueue >=0.6.1
    - tornado
    - coverage >=4.4
    - uncertainties
    - openmmtools
    - yank
    - pyyaml


  run:
    - python
    - pip

    # Testing and development
    - pytest
    - pytest-cov
    - codecov

    # Commercial
    - openeye-toolkits

    # Standard dependencies
    - openforcefield ==0.4.0
    - smirnoff99frosst
    - numpy
    - pandas
    - openmm
    - pint
    - packmol
    - pymbar
    - mdtraj
    - dask
    - distributed >=2.1
    - dask-jobqueue >=0.6.1
    - tornado
    - coverage >=4.4
    - uncertainties
    - openmmtools
    - yank
    - pyyaml
  
about:
  home: https://github.com/openforcefield/propertyestimator
  license: MIT
  license_file: LICENSE
  description: Property estimation toolkit from the Open Forcefield Consortium.
