package:
  name: pytools
  version: "2014.3.5"

source:
  fn: pytools-2014.3.5.tar.gz
  url: https://pypi.python.org/packages/source/p/pytools/pytools-2014.3.5.tar.gz
  md5: 7f8e9d6a88090a601e96a9ee095d3512

requirements:
  build:
    - python
    - setuptools
    - decorator >=3.2.0
    - appdirs >=1.4.0
    - six

  run:
    - python
    - decorator >=3.2.0
    - appdirs >=1.4.0
    - six

test:
  imports:
    - pytools

about:
  home: http://pypi.python.org/pypi/pytools
  license: MIT License
  summary: 'A collection of tools for Python'
