package:
  name: osprey
  version: "1.1.0"

source:
  git_url: https://github.com/msmbuilder/osprey.git
  git_tag: 1.1.0

build:
  number: 0
  entry_points:
    - osprey = osprey.cli.main:main
  skip:
    - [win]

extra:
  maintainers:
   - cxhernandez

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - pyyaml
    - numpy
    - scipy
    - scikit-learn
    - sqlalchemy

test:
  imports:
    - osprey
    - osprey.cli
    - osprey.plugins
    - osprey.plugins.tests
    - osprey.tests

  commands:
    - osprey --help


about:
  home: https://github.com/msmbuilder/osprey
  license: Apache Software License
  summary: 'osprey is the plumbing for machine learning hyperparameter optimization'

# vim: ts=2 sw=2 expandtab
