package:
  name: sh
  version: !!str 1.11

source:
  fn: sh-1.11.tar.gz
  url: https://pypi.python.org/packages/source/s/sh/sh-1.11.tar.gz
  md5: 7af8df6c92d29ff927b6db0146bddec3

build:
  skip:
    - [win]

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - sh

about:
  home: https://github.com/amoffat/sh
  license: MIT License
  summary: 'Python subprocess interface'
