package:
  name: parmed
  version: !!str 2.6.1

source:
  fn: ParmEd-2.6.1.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/2.6.1.tar.gz
  md5: e66ef98b34358f0fab3d3c6ee7bab775

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - openmm

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
