package:
  name: parmed
  version: !!str 2.7.3

source:
  fn: ParmEd-2.7.3.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/2.7.3.tar.gz
  
build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - pandas

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
