package:
  name: parmed
  version: !!str 2.0.5

source:
  fn: ParmEd-2.0-5.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/2.0.5.tar.gz
  md5: 7acb6537098a1bffc9b48dc0924ab9f0

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - openmm

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
