package:
  name: parmed
  version: !!str 2.5.1

source:
  fn: ParmEd-2.5.1.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/2.5.1.tar.gz
  md5: 8e301524254a63e0523243c059558d69

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - openmm

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
