package:
  name: parmed
  version: !!str 3.0.1

source:
  fn: ParmEd-3.0.1.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/3.0.1.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - numpy >=1.14
    - setuptools

  run:
    - python
    - numpy >=1.14
    - pandas

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
