package:
  name: cvxopt
  version: 1.1.8

source:
  fn: cvxopt-1.1.8.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxopt/cvxopt-1.1.8.tar.gz
  md5: d4ff0a0e51aba93f838a70302a088eea

  patches:
    - win-setup.patch  [win]


requirements:
  build:
    - python
    - mingwpy    [win]
    - openblas   [win]

  run:
    - python

test:
  imports:
    - cvxopt

about:
  home: http://cvxopt.org
  license: GNU GPL version 3
  summary: 'Convex optimization package'
