package:
  name: cvxopt
  version: "1.1.9"

source:
  fn: cvxopt-1.1.9.tar.gz
  url: https://pypi.python.org/packages/ef/90/38ccadcf77c8002ffd607fe1c14c67a4bf1041c990e8ba7aa4b8a2287350/cvxopt-1.1.9.tar.gz
  md5: a56e7b23d76c2b5aaf3bea2a7c245ea7

requirements:
  build:
    - python
    - mingwpy # [win]
    - openblas

  run:
    - python
    - openblas

test:
  imports:
    - cvxopt

about:
  home: http://cvxopt.org
  license: GNU GPL version 3
  summary: 'Convex optimization package'
