package:
  name: paramz
  version: "0.1.5"

source:
  fn: paramz-0.1.5.tar.gz
  url: https://pypi.python.org/packages/source/p/paramz/paramz-0.1.5.tar.gz
  md5: d3f39bc64cf8de37c7df85efd41333d9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - paramz = paramz:main
    #
    # Would create an entry point called paramz that calls paramz.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - scipy
    - six

  run:
    - python
    - numpy >=1.7
    - scipy
    - six

test:
  # Python imports
  imports:
    - paramz
    - paramz.core
    - paramz.examples
    - paramz.optimization
    - paramz.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mzwiessele/paramz
  license: BSD License
  summary: 'The Parameterization Framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
