package:
  name: swig
  version: 3.0.8

source:
  fn: swigwin-3.0.8.zip                                                     [win]
  url: http://prdownloads.sourceforge.net/swig/swigwin-3.0.8.zip            [win]
  sha256: e5fe65ae9b145ea3c00172abdb527f2d3458e8cc928e25db984b2da1b00a2a04  [win]
  fn: swig-3.0.8.tar.gz                                                 [not win]
  md5: c96a1d5ecb13d38604d7e92148c73c97                                 [not win]
  url: http://prdownloads.sourceforge.net/swig/swig-3.0.8.tar.gz        [not win]

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python  [not win]
    - pcre    [not win]
  run:
    - pcre    [not win]

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
    summary: "A tool that easily allows a developer to wrap C/C++ functions for use with scripting languages."
