package:
  name: numdifftools
  version: !!str 0.9.12

source:
  fn: numdifftools-0.9.12.zip
  url: https://pypi.python.org/packages/source/N/Numdifftools/numdifftools-0.9.12.zip
  md5: f1c3a80a08ca6ca21d7a8966ca5a97b0

build:
  skip:
    - True  # currently disabled. missing a package setuptools_scm

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.4
    - scipy >=0.8
    - six
    - algopy

  run:
    - python
    - numpy >=1.4
    - scipy >=0.8
    - six
    - algopy

test:
  # Python imports
  imports:
    - numdifftools
  requires:
    - matplotlib

about:
  home: http://code.google.com/p/numdifftools/
  license:  BSD License
  summary: 'Solves automatic numerical differentiation problems in one or more variables.'
