package:
  name: numdifftools
  version: "0.9.14"

source:
  fn: numdifftools-0.9.14.zip
  url: https://pypi.python.org/packages/source/N/Numdifftools/numdifftools-0.9.14.zip#md5=04add9a62433466923764d9ef501eeb5
  md5: 04add9a62433466923764d9ef501eeb5

requirements:
  build:
    - python
    - setuptools
    - six
    - pip
    - numpy
    - scipy
    - algopy

  run:
    - python
    - numpy
    - scipy
    - six
    - algopy

test:
  imports:
    - numdifftools

about:
  home: http://code.google.com/p/numdifftools/
  license:  BSD License
  summary: 'Solves automatic numerical differentiation problems in one or more variables.'
