package:
  name: gpy
  version: 0.8.8

source:
  url: https://github.com/SheffieldML/GPy/archive/v0.8.8.tar.gz
  fn: v0.8.8.tar.gz
  md5: f6ff0bba7cb8dc24c39dbb42b3ffa973
  patches:
    - 0001-Add-basesetup.py.patch
    - 0002-Add-compiler-detection-code-for-OpenMP.patch

requirements:
  build:
    - python
    - scipy
    - numpy
    - six
    - nose
    - paramz
    - cython

  run:
    - python
    - scipy
    - numpy
    - cython
    - six
    - paramz

about:
    home: http://sheffieldml.github.io/GPy/
    license: GPL3
