package:
  name: gpy
  version: 1.5.6

source:
  git_url: https://github.com/SheffieldML/GPy.git
  git_tag: v1.5.6

build:
  skip: True  # [win and py34]

extra:
  maintainers:
   - cxhernandez

requirements:
  build:
    - python
    - scipy
    - numpy
    - six
    - nose
    - paramz
    - cython

  run:
    - python
    - scipy
    - numpy
    - cython
    - six
    - paramz
    - matplotlib

test:
  imports:
    - GPy

about:
    home: http://sheffieldml.github.io/GPy/
    license: GPL3
