package:
    name: pyhmc
    version: !!str 0.1.2

source:
    git_url: https://github.com/rmcgibbo/pyhmc.git
    git_tag: 0.1.2

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy

test:
  requires:
    - nose
    - scipy
    - statsmodels
  imports:
    - pyhmc

about:
  home: https://github.com/rmcgibbo/pyhmc
  license: BSD
  summary: 'pyhmc: Hamiltonain Monte Carlo Sampling in Python'
