package:
    name: pyhmc
    version: "0.1.2"

source:
    url: https://pypi.python.org/packages/source/p/pyhmc/pyhmc-0.1.2.tar.gz
    md5: 83fad8eee823d5ac7a70faa994555a5a
    fn: pyhmc-0.1.2.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy

test:
  requires:
    - nose
    - scipy
    - statsmodels
  imports:
    - pyhmc

about:
  home: https://github.com/rmcgibbo/pyhmc
  license: BSD
  summary: 'pyhmc: Hamiltonain Monte Carlo Sampling in Python'
