package:
  name: nglview
  version: "0.6.2.2"

source:
  git_url: https://github.com/arose/nglview.git
  git_tag: v0.6.2.2

build:
  number: 1
  #noarch_python: True

requirements:
  build:
    - python
    - jupyter
    - ipywidgets >5.1.0
    - notebook >4.1
    - traitlets

  run:
    - python
    - numpy
    - ipywidgets >5.1.0
    - jupyter
    - traitlets
    - notebook >4.1

test:
  imports:
    - nglview

about:
  home: https://github.com/arose/nglview
  license: MIT License
  summary: 'An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.'
