package:
  name: nglview
  version: "v0.5.2"

source:
  fn: nglview-0.5.dev.tar.gz
  git_url: https://github.com/arose/nglview.git
  git_tag: v0.5.2

build:
  number: 0
  noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - ipywidgets <=4.1.1
    - traitlets

  run:
    - python
    - numpy
    - ipywidgets <=4.1.1
    - jupyter
    - traitlets
    - notebook

test:
  imports:
    - nglview

about:
  home: https://github.com/arose/nglview
  license: MIT License
  summary: 'An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.'
