package:
  name: lomap
  version: "1.0.0"
source:
  git_rev: 1.0.0
  git_url: https://github.com/nividic/Lomap.git

requirements:
  build:
    - python
    - setuptools
    - rdkit
    - matplotlib
    - pyqt
    - networkx >=1.11
    - graphviz
    - pygraphviz ==1.2
    - pil

  run:
    - python
    - rdkit 
    - matplotlib
    - pyqt
    - networkx
    - graphviz
    - pygraphviz
    - pil

about:
  home: https://github.com/nividic/Lomap
  license: LGPL
  license_file: LICENCE.txt  
