package:
  name: yank
  version: "0.24.0"

source:
    url: https://github.com/choderalab/yank/archive/0.24.0.tar.gz
    fn: 0.24.0.tar.gz

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  build:
    - python
    - cython
    - setuptools
    - numpy >=1.14

  run:
    - python
    - pandas
    - numpy >=1.14
    - scipy
    - cython
    - netcdf4 >=1.4.2 # after bugfix: "always return masked array by default, even if there are no masked values"
    - libnetcdf >=4.6.2 # workaround for libssl issues (see #1135)
    - openmm >=7.1
    - mdtraj >=1.7.2
    - openmmtools >=0.17.0
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools >=0.7.5
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus ==1.1
    - matplotlib
    - jupyter
    - pdbfixer

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: MIT
  license_file: LICENSE
