package:
  name: yank
  version: "0.23.7"

source:
    url: https://github.com/choderalab/yank/archive/0.23.7.tar.gz
    fn: 0.23.7.tar.gz

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  build:
    - python
    - cython
    - setuptools
    - numpy >=1.14

  run:
    - python
    - pandas
    - numpy >=1.14
    - scipy
    - cython
    - netcdf4 >=1.4.2
    - openmm >=7.1
    - mdtraj >=1.7.2
    - openmmtools >=0.15.0
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools >=0.7.5
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus >=1.1
    - matplotlib
    - jupyter
    - pdbfixer
    - libnetcdf >=4.6.0

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: MIT
  license_file: LICENSE
