package:
  name: yank
  version: 0.9.0

source:
    git_url: https://github.com/choderalab/yank.git
    git_tag: 0.9.0

build:
  number: 0
  skip:
    - [win]
    - [osx and py3k]
    - [unix and py3k]

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm  ==7.0.1
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)
    - openmmtools ==0.7.5
    - pymbar ==2.1beta0
    - ambermini ==14.0.1
    - docopt
    - openmoltools ==0.7.1
    - sphinxcontrib-bibtex
    - alchemy ==1.2.0
    - schema >=0.5.0
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm ==7.0.1
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)
    - openmmtools ==0.7.5
    - pymbar ==2.1beta0
    - ambermini ==14.0.1
    - docopt
    - openmoltools ==0.7.1
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - alchemy ==1.2.0
    - schema >=0.5.0
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help
    - yank selftest

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
