package:
  name: yank
  version: 0.7.0

source:
    git_url: https://github.com/choderalab/yank.git
    git_tag: 0.7.0

build:
  number: 1
  skip:
    - [win32 or (win and py2k)]  # for openmm
    - [py3k]   # this package is not p3k compatible yet

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools
    - pymbar ==2.1beta0
    - ambermini ==14.0.1
    - docopt
    - openmoltools
    - jinja2

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm
    - openmmtools
    - pymbar ==2.1beta0
    - ambermini ==14.0.1
    - docopt
    - openmoltools
    - mpi4py
    - pyyaml
    - jinja2
    - clusterutils

test:
  requires:
    - nose
  imports:
    - yank
  commands:
    - which yank
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: GPU-accelerated calculation of ligand binding affinities in implicit and explicit solvent using alchemical free energy methodologies
