package:
  name: yank
  version: "0.20.0"

source:
    url: https://github.com/choderalab/yank/archive/0.20.0.tar.gz
    fn: 0.20.0.tar.gz

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm >=7.1
    - mdtraj >=1.7.2
    - openmmtools >=0.13.4
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools
    - sphinxcontrib-bibtex
    - cerberus
    - matplotlib
    - jupyter
    - pdbfixer
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm >=7.1
    - mdtraj >=1.7.2
    - openmmtools >=0.13.4
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools >=0.7.5
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus
    - matplotlib
    - jupyter
    - pdbfixer
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: MIT License
