package:
  name: yank
  version: 0.8.0

source:
    git_url: https://github.com/choderalab/yank.git
    git_tag: 0.8.0

build:
  number: 0
  skip:
    - [win32 or (win and py2k)]  # for openmm
    - [py3k]   # this package is not p3k compatible yet

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm ==7.0rc1 # temporarily test against stable version
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)
    - openmmtools ==0.7.5 # temporarily test against stable version
    - pymbar ==2.1beta0 # temporarily test against stable version
    - ambermini ==14.0.1 # temporarily test against stable version
    - docopt
    - openmoltools ==0.7.0 # temporarily test against stable version
    - sphinxcontrib-bibtex
    - alchemy ==1.2.0
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm ==7.0rc1 # temporarily test against stable version
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)
    - openmmtools ==0.7.5 # temporarily test against stable version
    - pymbar ==2.1beta0 # temporarily test against stable version
    - ambermini
    - docopt
    - openmoltools ==0.7.0 # temporarily test against stable version
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - alchemy ==1.2.0
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help
    - yank selftest

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
