package:
  name: packmol
  version: 2016.06.09

source:
  fn: packmol.tar.gz
  url: http://www.ime.unicamp.br/~martinez/packmol/packmol.tar.gz

build:
  number: 1
  # no mingwpy support for py35 on win
  skip: True  # [win and py35] 

requirements:
  build:
    - zlib
    - python
    - mingwpy  [win]
    - gcc      [unix]
    - libgfortran ==1.0 [linux]
  run:
    - zlib
    - libgcc   [unix]
    - libgfortran ==1.0 [linux]

test:
  commands:
    - which packmol

about:
  home: http://www.ime.unicamp.br/~martinez/packmol/
  license: GPL
  summary: Packing Optimization for Molecular Dynamics Simulations
