package:
  name: packmol
  version: 1.0.0

source:
  fn: packmol.tar.gz
  url: http://www.ime.unicamp.br/~martinez/packmol/packmol.tar.gz

build:
  number: 3

requirements:
  build:
    - zlib
    - python
    - mingwpy  [win]
    - gcc      [unix]
    - libgfortran ==1.0 [linux]
  run:
    - zlib
    - libgcc   [unix]
    - libgfortran ==1.0 [linux]

test:
  commands:
    - which packmol

about:
  home: http://www.ime.unicamp.br/~martinez/packmol/
  license: GPL
  summary: Packing Optimization for Molecular Dynamics Simulations
