package:
  name: thermotools
  version: 0.2.6
source:
  fn: thermotools-0.2.6.tar.gz
  url: https://github.com/markovmodel/thermotools/archive/0.2.6.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy x.x
    - scipy >=0.11
    - msmtools >=1.1.3

  run:
    - python
    - numpy x.x
    - scipy >=0.11
    - msmtools >=1.1.3

test:
  imports:
    - thermotools

about:
  home: https://github.com/markovmodel/thermotools
  license: GNU Lesser Public License v3+
  summary: "Lowlevel implementation toolbox for the analyis of multi-ensemble calculations"
