package:
  name: openmm
  version: 6.3

source:
  url: https://github.com/pandegroup/openmm/archive/6.3.tar.gz
  fn: 6.3.tar.gz

build:
  number: 0
  preserve_egg_dir: yes
  skip:
    - [win32 or (win and py2k)]

requirements:
  build:
    # on windows, need to install cmake manually
    - cmake     [not win]
    - python
    - fftw3f
    - sphinx
    - sphinxcontrib-bibtex
    - swig
    - doxygen   [win]
    - jom       [win]
  run:
    - python
    - fftw3f

test:
  requires:
    - python
  imports:
    - simtk
    - simtk.openmm
  commands:
    - python -m simtk.testInstallation

about:
  home: http://openmm.org
  license: LGPL and MIT
  summary: A high performance toolkit for molecular simulation.
