package:
  name: openmmtools
  version: 0.7.4

source:
    fn: 0.7.4.tar.gz
    git_url: https://github.com/choderalab/openmmtools/archive/0.7.4.tar.gz
    md5: 99f474fa3796395103c846ff622c5cbd

build:
  preserve_egg_dir: True
  number: 0
  skip:
    - [win32 or (win and py2k)]

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - nose
    - setuptools
    - openmm
    - jinja2
    - parmed

  run:
    - python
    - scipy
    - openmm
    - nose
    - setuptools
    - jinja2
    - six
    - parmed

test:
  requires:
    - nose
  imports:
    - openmmtools
  #commands:
  #  - nosetests openmmtools --with-doctest --verbosity=2 --nocapture

about:
  home: https://github.com/choderalab/openmmtools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Test systems for OpenMM
