package:
  name: openmmtools
  version: 0.12.1

source:
    fn: 0.12.1.tar.gz
    url: https://github.com/choderalab/openmmtools/archive/0.12.1.tar.gz

build:
  number: 0
  skip: True  # [win32 or (win and py2k)]

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - openmm
    - jinja2
    - parmed
    - mdtraj

  run:
    - python
    - cython
    - numpy
    - scipy
    - openmm
    - setuptools
    - jinja2
    - six
    - parmed
    - mdtraj

test:
  requires:
    - nose
    - pymbar
  imports:
    - openmmtools


about:
  home: https://github.com/choderalab/openmmtools
  license: MIT
  summary: "An OpenMM toolkit: test systems, integrators, and alchemical support"
