package:
  name: openmmtools
  version: 0.9.2

source:
    fn: 0.9.2.tar.gz
    url: https://github.com/choderalab/openmmtools/archive/0.9.2.tar.gz

build:
  number: 0
  skip: True  # [win32 or (win and py2k)]

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - nose
    - setuptools
    - openmm
    - jinja2
    - parmed

  run:
    - python
    - scipy
    - openmm
    - nose
    - setuptools
    - jinja2
    - six
    - parmed

test:
  requires:
    - pymbar
  imports:
    - openmmtools
    

about:
  home: https://github.com/choderalab/openmmtools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Test systems for OpenMM
