package:
  name: openmmtools
  version: 0.17.0

source:
    fn: 0.17.0.tar.gz
    url: https://github.com/choderalab/openmmtools/archive/0.17.0.tar.gz

build:
  number: 0
  skip: True  # [py2k or win32]

requirements:
  build:
    - python
    - cython
    - numpy >=1.14
    - scipy
    - setuptools
    - openmm >=7.3
    - jinja2
    - parmed
    - mdtraj
    - netcdf4
    - pyyaml

  run:
    - python
    - cython
    - numpy >=1.14
    - scipy
    - openmm >=7.3
    - setuptools
    - jinja2
    - six
    - parmed
    - mdtraj
    - netcdf4
    - pyyaml

test:
  requires:
    - nose
    - pymbar
  imports:
    - openmmtools


about:
  home: https://github.com/choderalab/openmmtools
  license: MIT
  summary: "An OpenMM toolkit: test systems, integrators, and alchemical support"
