package:
  name: openmmtools
  version: 0.8.0

source:
    fn: 0.8.0.tar.gz
    url: https://github.com/choderalab/openmmtools/archive/0.8.0.tar.gz

build:
  number: 1
  skip:
    - [win32 or (win and py2k)]
    # TODO no openmm py35 win
    - [win and py35]

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - nose
    - setuptools
    - openmm
    - jinja2
    - parmed

  run:
    - python
    - scipy
    - openmm
    - nose
    - setuptools
    - jinja2
    - six
    - parmed

test:
  requires:
    - nose
  imports:
    - openmmtools
  #commands:
  #  - nosetests openmmtools --with-doctest --verbosity=2 --nocapture

about:
  home: https://github.com/choderalab/openmmtools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Test systems for OpenMM
