package:
  name: pymbar
  version: 3.0.0.beta2

source:
  url: https://github.com/choderalab/pymbar/archive/3.0.0.beta2.zip
  fn: 3.0.0.beta2.zip

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy

  run:
    - python
    - numpy x.x
    - scipy

test:
  commands:
    - nosetests
  imports:
    - pymbar
    - pymbar.bar

  requires:
    - nose

about:
  home: http://github.com/choderalab/pymbar
  license: LGPL
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR).
