package:
  name: pymbar
  version: "3.0.1.beta0"

source:
  git_url: https://github.com/choderalab/pymbar.git
  git_tag: "3.0.1.beta0"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - six
    - numexpr

  run:
    - python
    - numpy x.x
    - scipy
    - six
    - numexpr

test:
  commands:
    - nosetests
  imports:
    - pymbar
    - pymbar.bar
  requires:
    - nose
  commands:
    #- nosetests pymbar -vv --with-doctest --nocapture

about:
  home: http://github.com/choderalab/pymbar
  license: LGPL
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR).
