package:
  name: termcolor
  version: "1.1.0"

source:
  fn: termcolor-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/t/termcolor/termcolor-1.1.0.tar.gz
  md5: 043e89644f8909d462fbbfa511c768df

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - termcolor

about:
  home: http://pypi.python.org/pypi/termcolor
  license: MIT License
  summary: 'ANSII Color formatting for output in terminal.'
