package:
  name: assaytools
  version: 0.3.0

source:
    git_url: https://github.com/choderalab/assaytools.git
    git_tag: 0.3.0

build:
  number: 0
  skip: True # [win]

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - pint
    - pandas
    - scipy
    - pymc
    - matplotlib
    - seaborn
    - lxml

test:
  requires:
    - nose
    - scripttest
    - pint
    - numpy
    - scipy
    - pymc
    - matplotlib
    - seaborn
    - lxml
  imports:
    - assaytools

about:
  home: http://assaytools.choderalab.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A library for the modeling and analysis of plate-based assays (development snapshot)
