package:
  name: shiftx2
  version: "1.10"

source:
  fn: shiftx2-v110-linux-20160912.tgz
  url: http://www.shiftx2.ca/download/shiftx2-v110-linux-20160912.tgz
  md5: be650b7cbc76034e2c4e77373e389fbc
  patches:
    - gcc.patch

build:
  number: 0
  skip: True  # [not (py2k and linuex)]

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - shiftx2.py -h

about:
  home: http://www.shiftx2.ca/
  license: All rights reserved
  summary: SHIFTX2 predicts both the backbone and side chain 1H, 13C and 15N
      chemical shifts for proteins using their structural (PDB) coordinates as
      input.

# vim: ts=2 sw=2 et
