package:
  name: openpathsampling
  version: 1.0

source:
  git_url: https://github.com/openpathsampling/openpathsampling.git
  git_tag: v1.0

build:
  preserve_egg_dir: True
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14
    - scipy
    - future
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - jupyter
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - ujson
    - pyemma

  run:
    - python
    - numpy >=1.14
    - scipy
    - future
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - jupyter
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - ujson
    - pyemma

#test:
  #imports:
    #- openpathsampling

about:
  home: http://github.com/openpathsampling/openpathsampling
  license: MIT
  summary: 'OpenPathSampling: A python package to do path sampling simulations'
