package:
  name: openmoltools
  version: 0.8.4

source:
    url: https://github.com/choderalab/openmoltools/archive/0.8.4.tar.gz
    fn: 0.8.4.tar.gz

build:
  number: 1
  skip: True # [win32 or (win and py2k)]

requirements:
  build:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy >=1.14
    - numpydoc
    - scipy
    - pandas
    - openmm >=7.0.1
    - ambermini
    - pytables
    - parmed

  run:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy >=1.14
    - numpydoc
    - scipy
    - openmm >=7.0.1
    - ambermini
    - pytables
    - parmed

test:
  requires:
    - nose
    - openmmtools
  imports:
    - openmoltools
  #commands:
  #  - nosetests openmoltools -v -a '!slow'

about:
  home: https://github.com/choderalab/openmoltools
  license: MIT License
