package:
  name: yank-examples
  version: "1.0.0"

source:
    git_url: https://github.com/choderalab/yank-examples.git
    git_tag: "1.0.0"

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - yank >=0.14.1
    - ambermini >=16.16.0


  run:
    - yank >=0.14.1
    - ambermini >=16.16.0

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank-examples
  license: MIT License
