package:
  name: fahmunge
  version: 0.3.0

source:
   url: https://github.com/choderalab/fahmunge/archive/0.3.0.tar.gz
   fn: 0.3.0.tar.gz

build:
  preserve_egg_dir: True
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - setuptools
    - python
    - numpy
    - pandas
    - pytables
    - natsort
    - mdtraj

  run:
    - python
    - numpy
    - pandas
    - pytables
    - natsort
    - mdtraj

test:
  requires:
    - nose
    - nose-timer
  imports:
    - fahmunge
  commands:
    - nosetests fahmunge --nocapture --verbosity=2 --with-doctest --with-timer
    - munge-fah-data --help
    - munge-fah-data --version

about:
  home: https://github.com/choderalab/fahmunge
  license: MIT License
