package:
  name: clusterutils
  version: "0.3.1"

source:
   url: https://github.com/choderalab/clusterutils/archive/0.3.1.tar.gz
   fn: 0.3.1.tar.gz

build:
  number: 1
  entry_points:
    - build_mpirun_configfile = clusterutils.build_mpirun_configfile:main
  skip: True  # [not unix]
    
requirements:
  build:
    - python
    - setuptools
    - mpich

  run:
    - python
    - mpich  # The current version is not compatible with OpenMPI.

about:
  home: https://github.com/choderalab/clusterutils
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Tools for use in compute cluster environments.
