package:
  name: alchemy
  version: 1.1.1

source:
  url: https://github.com/choderalab/alchemy/archive/1.1.1.zip
  fn: 1.1.1.zip

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm >=6.3
    - numpy

  run:
    - python
    - openmm >=6.3
    - numpy

test:
  imports:
    - alchemy

about:
  home: https://github.com/choderalab/alchemy
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Alchemical tools for OpenMM
