package:
  name: alchemy
  version: 1.2.2

source:
  url: https://github.com/choderalab/alchemy/archive/1.2.2.zip
  fn: 1.2.2.zip

build:
  number: 0
  skip:
    - [win and py27]
    - [win32]

requirements:
  build:
    - python
    - setuptools
    - openmm >=7.0.1
    - numpy

  run:
    - python
    - openmm >=7.0.1
    - numpy

test:
  imports:
    - alchemy

about:
  home: https://github.com/choderalab/alchemy
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Alchemical tools for OpenMM
