package:
  name: alchemy
  version: 1.2.3

source:
  url: https://github.com/choderalab/alchemy/archive/1.2.3.zip
  fn: 1.2.3.zip

build:
  number: 0
  skip: True  # [win32 or (win and py27)]

requirements:
  build:
    - python
    - setuptools
    - openmm >=7.0.1
    - numpy
    - openmmtools

  run:
    - python
    - openmm >=7.0.1
    - numpy
    - openmmtools

test:
  imports:
    - alchemy

about:
  home: https://github.com/choderalab/alchemy
  license: MIT License
  summary: Alchemical tools for OpenMM
