package:
  name: msmexplorer
  version: "1.0.0"

source:
  git_url: https://github.com/msmexplorer/msmexplorer.git
  git_tag: 1.0.0

build:
  number: 0
  skip: True  # [py27]

extra:
  maintainers:
   - cxhernandez

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - msmbuilder
    - mdtraj
    - matplotlib
    - seaborn
    - statsmodels
    - networkx
    - corner

about:
  home: https://github.com/msmexplorer/msmexplorer
  license: MIT
  summary: 'Data visualizations for biomolecular dynamics'

# vim: ts=2 sw=2 et
