package:
  name: msmtools 
  version: !!str 1.1

source:
  fn: v1.1.zip
  url: https://github.com/markovmodel/msmtools/archive/v1.1.zip 

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy x.x
    - scipy 
    - nose
    - six

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - six

test:
  imports:
    - msmtools 

about:
  home: http://emma-project.org
  license: LGPLv3+ 
  summary: "MSMTools"
