package:
  name: cvxcanon
  version: "0.0.22"

source:
  git_url: https://github.com/cvxgrp/CVXcanon.git
  git_tag: "0.0.23"

requirements:
  build:
    - python
    - numpy x.x
    - scipy

  run:
    - python
    - numpy x.x
    - scipy

test:
  imports:
    # - CVXcanon

about:
  home: https://github.com/cvxgrp/CVXcanon
  license: Apache2.0
  summary: "A low-level library to perform the matrix building step in cvxpy, a convex optimization modeling software."


