package:
  name: cvxcanon
  version: "0.0.21"

source:
  fn: CVXcanon-0.0.21.tar.gz
  url: https://pypi.python.org/packages/source/C/CVXcanon/CVXcanon-0.0.21.tar.gz
  md5: 815fe7a87455d1e17cae63046bffa12c

requirements:
  build:
    - python
    - numpy x.x
    - scipy

  run:
    - python
    - numpy x.x
    - scipy

test:
  imports:
    # - CVXcanon

about:
  home: https://github.com/cvxgrp/CVXcanon
  license: GPLv3
  summary: 'A low-level library to perform the matrix building step in cvxpy, a convex optimization modeling software.'


