package:
  name: scs
  version: !!str 1.1.7

source:
  fn: scs-1.1.7.tar.gz
  url: https://pypi.python.org/packages/source/s/scs/scs-1.1.7.tar.gz
  md5: 4ff95eb4ad76f7fdea53263871d41eee

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - clapack
    - numpy x.x
    - scipy

  run:
    - python
    - numpy x.x
    - scipy

test:
  requires:
    - nose
  # Python imports
  imports:
    - scs

about:
  home: http://github.com/cvxgrp/scs
  license: GPLv3
  summary: 'scs: splittling cone solver'
