package:
  name: scs
  version: "1.2.6"

source:
  fn: scs-1.2.6.tar.gz
  url: https://pypi.python.org/packages/94/b0/7517c1113c121db1b9cc19a381f28fc915294eaa61f61e0a3502746dfa88/scs-1.2.6.tar.gz
  md5: 3eaa04ffa76aaf27dc8a8e608c6a9f12

build:
  number: 1
  skip:
    # no mingwpy py35
    - [win and py35]
    # mingwpy doesn't work with py3k for numpy < 1.10
    # https://github.com/numpy/numpy/issues/3557
    - [win and np == 19 and py3k]


requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - mingwpy [win]

  run:
    - python
    - numpy x.x
    - scipy


test:
  requires:
    - nose
  imports:
    - scs

about:
  home: http://github.com/cvxgrp/scs
  license: GPLv3
  summary: 'scs: splittling cone solver'
