package:
  name: scs
  version: !!str 1.1.7

source:
  fn: scs-1.1.7.tar.gz
  url: https://pypi.python.org/packages/source/s/scs/scs-1.1.7.tar.gz
  md5: 4ff95eb4ad76f7fdea53263871d41eee
  patches:
    - 0001-set-zip-safe-flag-to-false.patch

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - openblas
    - mingwpy [win]

  run:
    - python
    - numpy x.x
    - scipy
    # openblas linked statically on windows, dynamically otherwise
    - openblas [not win]

test:
  requires:
    - nose
  imports:
    - scs

about:
  home: http://github.com/cvxgrp/scs
  license: GPLv3
  summary: 'scs: splittling cone solver'
