package:
  name: openmm-setup
  version: 1.1

source:
  git_url: https://github.com/pandegroup/openmm-setup.git
  git_tag: fc94b50

extra:
  upload: beta
  force_upload: False
  include_omnia_label: beta

build:
  number: 0
  entry_points:
    - openmm-setup = openmmsetup.openmmsetup:main
  skip: True  # [win32 or (win64 and not py35)]

requirements:
  build:
    - python
    - setuptools
    - flask
    - openmm
    - pdbfixer >=1.5

  run:
    - python
    - flask
    - openmm
    - pdbfixer >=1.5

about:
  home: http://github.com/pandegroup/openmm-setup
  license: MIT
  summary: An application for configuring and running simulations with OpenMM
