package:
  name: schema
  version: !!str 0.5.0

source:
  fn: schema-0.5.0.tar.gz
  url: https://pypi.python.org/packages/4b/eb/fadd6bc4967fded31495ea70aebd3bdc90b83e3944d08bfd841039062f83/schema-0.5.0.tar.gz
  md5: cee375ebfa54f1c4a218438b3b1c6803

build:
  skip:
    - [py3k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - schema

about:
  home: http://github.com/halst/schema
  license: MIT License
  summary: 'Simple data validation library'
