package:
  name: schema
  version: !!str 0.3.1

source:
  fn: schema-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/s/schema/schema-0.3.1.tar.gz
  md5: 241d4f8211ebab33bc28be90a300cb58

build:
  skip:
    - [py3k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - schema

about:
  home: http://github.com/halst/schema
  license: MIT License
  summary: 'Simple data validation library'
