package:
  name: ecos
  version: "2.0.4"

source:
  fn: ecos-2.0.4.tar.gz
  url: https://pypi.python.org/packages/source/e/ecos/ecos-2.0.4.tar.gz
  md5: 39cc4c4a5598cc51ca4dc9aec810f41a

build:
  skip: True # [win and (py35 or py36)]
  # Disable for now under certain windows conditions

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.12

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.12

test:
  requires:
    - nose
  imports:
    - ecos

about:
  home: https://github.com/embotech/ecos
  license: GPLv3
  summary: 'A lightweight conic solver for second-order cone programming.'
