package:
  name: quadprog
  version: "0.1.2"

build:
    string: py{{ py }}

source:
  fn: quadprog-0.1.2.tar.gz
  url: https://pypi.python.org/packages/source/q/quadprog/quadprog-0.1.2.tar.gz
  md5: 176a5384beae041ebb97541615cb83c5

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - mingwpy   [win]

  run:
    - python
    - numpy

test:
  imports:
    - quadprog

about:
  home: https://github.com/rmcgibbo/quadprog
  license: GPLv2+
  summary: 'Quadratic Programming Solver'
