package:
  name: smirnoff99Frosst
  version: "1.0.9"

source:
  git_url: https://github.com/openforcefield/smirnoff99Frosst.git
  git_tag: all-versions

build:
  number: 0
  entry_points:
    - smirnoff99Frosst = smirnoff99Frosst.smirnoff99Frosst:main
  skip: True  # [win32 or (win and py2k)]

extra:
 upload: beta
 include_omnia_label: beta

about:
  home: https://github.com/openforcefield/smirnoff99Frosst
  license: CC-BY
  summary: 'The smirnoff99Frosst line of force fields, used by the Open Force Field Consortium'
