package:
  name: smirnoff99frosst
  version: "1.1.0"

source:
  git_url: https://github.com/openforcefield/smirnoff99frosst.git
  git_tag: master

build:
  number: 0
  entry_points:
    - smirnoff99frosst = smirnoff99frosst.smirnoff99frosst:main
  skip: True  # [win32 or (win and py2k)]

extra:
 upload: main
# include_omnia_label: rc

about:
  home: https://github.com/openforcefield/smirnoff99frosst
  license: CC-BY
  summary: 'The smirnoff99Frosst line of force fields'

requirements:
  build:
    - python
    - cython
    - setuptools
    
