package:
  name: pint
  version: !!str 0.6

source:
  fn: Pint-0.6.zip
  url: https://pypi.python.org/packages/source/P/Pint/Pint-0.6.zip
  md5: 88aa0918019071546b10c5fbdc91ae5e

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - pint

about:
  home: https://github.com/hgrecco/pint
  license: BSD License
  summary: 'Physical quantities module'
