package:
  name: progress_reporter
  version: "1.3.1"

source:
  git_url: https://github.com/marscher/progress_reporter
  git_rev: v1.3.1

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
     # np required for py36 and VersionIter skipping, https://github.com/omnia-md/conda-recipes/issues/712
    - numpy x.x
  run:
    - python

test:
  # Python imports
  imports:
    - progress_reporter
    - progress_reporter.bar

about:
  home: https://github.com/marscher/progress_reporter
  license: MIT License
  summary: 'interface for progress reporting'

extra:
  maintainers: Martin Scherer
