package:
  name: msmb_data
  version: "2.0.0"

source:
  git_url: https://github.com/msmbuilder/msmb_data.git
  git_tag: v2.0

extra:
  maintainers:
   - cxhernandez
   - mpharrigan

about:
  home: https://github.com/msmbuilder/msmb_data
  license: CC-BY
  summary: 'Testing data for MSMBuilder'
