package:
  name: openmoltools
  version: 0.7.0

source:
    git_url: https://github.com/choderalab/openmoltools.git
    git_tag: v0.7.0


build:
  number: 1
  skip:
    - [win32 or (win and py2k)]
    # TODO no openmm py35 win
    - [win and py35]

requirements:
  build:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy
    - numpydoc
    - scipy
    - pandas
    - openmm
    - ambermini
    - pytables
    - parmed
#    - rdkit    # rdkit is an optional dependency, may want to comment this out for the release version.
  run:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy
    - numpydoc
    - scipy
    - openmm
    - ambermini
    - pytables
    - parmed
    - libgfortran 1.* # [linux and np == 19]
#    - rdkit    # rdkit is an optional dependency, may want to comment this out for the release version.

test:
  requires:
    - nose
    - openmmtools
  imports:
    - openmoltools
  commands:
    - nosetests openmoltools -v -a '!slow'

about:
  home: https://github.com/choderalab/openmoltools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
