package:
  name: doxygen
  version: 1.8.10

source:
  fn: doxygen-1.8.10.windows.bin.zip                                             [win64]
  url: http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.windows.bin.zip      [win64]
  fn: doxygen-1.8.10.windows.x64.bin.zip                                         [win32]
  url: http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.windows.x64.bin.zip  [win32]
  url: http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.src.tar.gz           [not win]
  fn: doxygen-1.8.10.src.tar.gz                                                  [not win]

build:
  skip:
    - [ osx ]

requirements:  [not win]
  build:       [not win]
    - m4       [not win]
    - cmake    [not win]
    - bison    [not win]
    - flex     [not win]

test:
  commands:
    - doxygen -v

about:
    home: http://www.stack.nl/~dimitri/doxygen/index.html
    license: GPLv3
    summary: "Doxygen is the de facto standard tool for generating documentation from annotated C++ sources"

