package:
    name: covar
    version: "0.2"

source:
    fn: covar-0.2.tar.gz
    url: https://pypi.python.org/packages/source/c/covar/covar-0.2.tar.gz
    md5: 843ffc591132cab0f8b374891aa8f4ff

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy >=0.16
  run:
    - python
    - setuptools
    - numpy
    - scipy >=0.16

test:
  imports:
    - covar

about:
  home: https://github.com/rmcgibbo/covar
  license: BSD
  summary: 'covar: shrinkage covariance estimation'
