package:
  name: nose-timer
  version: "0.5.0"

source:
  fn: nose-timer-0.5.0.tar.gz
  url: https://pypi.python.org/packages/source/n/nose-timer/nose-timer-0.5.0.tar.gz
  md5: 7f9bc6e0eae50d588a9d08d809cddd3f

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - nose
    - termcolor

  run:
    - python
    - setuptools
    - nose
    - termcolor

test:
  # Python imports
  imports:
    - nosetimer

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mahmoudimus/nose-timer
  license: MIT License or BSD License
  summary: 'A timer plugin for nosetests'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
