package:
  name: cvxpy
  version: "0.4.8"

build:
  number: 0
  # No mingwpy on python 3.5+ which is needed by cvxp[t
  skip: True # [win and (py35 or py36)]

source:
  git_url: https://github.com/cvxgrp/cvxpy

requirements:
  build:
    - python
    - numpy
    - scipy
    - multiprocess
    - toolz
    - scs
    - ecos
    - cvxopt
    - setuptools
    - cvxcanon >=0.0.22
    - six
    - fastcache

  run:
    - python
    - numpy
    - scipy
    - multiprocess
    - toolz
    - scs
    - ecos
    - cvxopt
    - cvxcanon >=0.0.22
    - six
    - fastcache

test:
  requires:
    - setuptools
  imports:
    - cvxpy

about:
  home: http://www.cvxpy.org/en/latest/
  license: Apache2.0
  summary: 'A Python-embedded modeling language for convex optimization.'
