package:
  name: cvxpy
  version: "0.4.8"

build:
  number: 0

source:
  git_url: https://github.com/cvxgrp/cvxpy

requirements:
  build:
    - python
    - numpy
    - scipy
    - multiprocess
    - toolz
    - scs
    - ecos
    - cvxopt
    - setuptools
    - cvxcanon >=0.0.22
  run:
    - python
    - numpy
    - scipy
    - multiprocess
    - toolz
    - scs
    - ecos
    - cvxopt
    - cvxcanon >=0.0.22
test:
  requires:
    - setuptools
  imports:
    - cvxpy

about:
  home: http://www.cvxpy.org/en/latest/
  license: Apache2.0
  summary: 'A Python-embedded modeling language for convex optimization.'
