{% set version = "2.2.6" %}

package:
  name: pyemma
  version: {{ version }}
source:
  fn: pyEMMA-{{ version }}.tar.gz
  url: https://github.com/markovmodel/PyEMMA/archive/v{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20

    - mdtraj >=1.7
    - nose
    - numpy x.x

  run:
    - python
    - setuptools
    - bhmm >=0.6,<0.7
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.7 
    - mock
    - funcsigs
    - msmtools
    - thermotools >=0.2
    - numpy x.x
    - pyyaml
    - scipy
    - six
    - psutil >=3.1.1
    - decorator >=4.0.0
    - progress_reporter

test:
  imports:
    - pyemma

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"

