package:
  name: corner
  version: "2.0.0"

source:
  git_url: https://github.com/dfm/corner.py.git
  git_tag: v2.0.0

build:
  number: 0

extra:
  maintainers:
   - cxhernandez

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib

  run:
    - python
    - matplotlib
    - numpy
    - scipy
    - pandas

#test:
  #imports:
  #  - corner
  # Run "run_test.py" to force Matplotlib to use the PyQt5 instead of 4 (matplotlib issue)
  # See ongoing issue (https://github.com/ContinuumIO/anaconda-issues/issues/1068)



about:
  home: https://github.com/dfm/corner.py
  license: Berkeley Software Distribution (BSD)
  summary: 'Make some beautiful corner plots.'

# vim: ts=2 sw=2 expandtab
