package:
  name: openforcefields
  version: "1.0.0rc1"

source:
  git_url: https://github.com/openforcefield/openforcefields.git
  git_tag: master

build:
  number: 2
  #noarch: python
  entry_points:
    - openforcefields = openforcefields.openforcefields:main
  skip: True  # [win32 or (win and py2k)]

extra:
 upload: rc
 include_omnia_label: rc

about:
  home: https://github.com/openforcefield/openforcefields
  license: CC-BY
  summary: 'Force fields released by the Open Force Field Initiative'

requirements:
  build:
    - python
    - cython
    - setuptools
  run:
    - python
    - cython
    - setuptools
