package:
  name: mdtraj
  version: "1.5.1"

source:
  fn: mdtraj-1.5.1.tar.gz
  url: https://pypi.python.org/packages/source/m/mdtraj/mdtraj-1.5.1.tar.gz#md5=fe21b3023a398fa918f23351c5079cc9
  md5: fe21b3023a398fa918f23351c5079cc9

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
    - scripttest

  run:
    - python
    - numpy x.x
    - scipy
    - pandas
    - scripttest

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
