package:
  name: mdtraj
  version: "1.6.1"

source:
  fn: mdtraj-1.6.1.tar.gz
  url: https://pypi.python.org/packages/source/m/mdtraj/mdtraj-1.6.1.tar.gz#md5=867ace28bf592af866745f4dc4acd9c2
  md5: 867ace28bf592af866745f4dc4acd9c2

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - pytables

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
