package:
  name: mdtraj
  version: !!str 0.8.0

source:
  fn: mdtraj-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mdtraj/mdtraj-0.8.0.tar.gz#md5=c1b020953144e63a242cf7323dc89f98
  patches:
      - windows-mdtraj-0.8.patch

build:
  number: 1
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - pytables
    - scipy
    - pandas

test:
  # Python imports
  imports:
    - mdtraj

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - python -c "import mdtraj; mdtraj.test()"

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - setuptools
    - nose
    - pandas
    - scripttest

about:
  home: http://rmcgibbo.github.io/mdtraj
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
