package:
  name: mdtraj
  version: "1.7.2"

source:
  fn: mdtraj-1.7.2.tar.gz
  url: https://pypi.python.org/packages/bf/81/6f611041374bd7d2d49a15040d999cc52eed1a44e856a4a8d9c02370ac37/mdtraj-1.7.2.tar.gz#md5=f7880d56400cb0abc68603298877843a
  md5: f7880d56400cb0abc68603298877843a

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - pytables

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
