package:
  name: python-coveralls
  version: "2.9.0"

source:
  fn: python-coveralls-2.9.0.tar.gz
  url: https://pypi.python.org/packages/a7/75/c07d88092ad2eeab254abd86c526c5577365be22f8927e9215970973ed6e/python-coveralls-2.9.0.tar.gz
  md5: 959adccf213412fd851b24e44176521c

build:
  entry_points:
    - coveralls = coveralls:wear
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - requests
    - coverage >=4.0.3
    - six

  run:
    - python
    - pyyaml
    - requests
    - coverage >=4.0.3
    - six

test:
  # Python imports
  imports:
    - coveralls

  commands:
    - coveralls --help

about:
  home: http://github.com/z4r/python-coveralls
  license: Apache License 2.0
  summary: 'Python interface to coveralls.io API'
