package:
  name: msmbuilder
  version: "3.4.0"

source:
    fn: msmbuilder-3.4.0.tar.gz
    url: https://pypi.python.org/packages/source/m/msmbuilder/msmbuilder-3.4.0.tar.gz#md5=e9ab6ce08dfb7589ae772b51ed4da145
    md5: e9ab6ce08dfb7589ae772b51ed4da145

build:
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main
  skip:
    # https://github.com/ContinuumIO/anaconda-issues/issues/557
    # https://github.com/msmbuilder/msmbuilder/issues/715
    # https://github.com/omnia-md/conda-recipes/pull/424
    - [win32 and py35 and np == 19]


requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - mdtraj
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc # [not (win32 and py35 and np == 19)]
    - libgfortran 1.* # [linux and py35 and np == 19]


test:
  requires:
    - nose
    - munkres
    - numdifftools
    - statsmodels
    - hmmlearn
    - cvxpy # [not win]
  imports:
    - msmbuilder
  commands:
    - msmb -h


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'
