package:
  name: msmbuilder
  version: "3.5.0"

source:
    fn: msmbuilder-3.5.0.tar.gz
    url: https://pypi.python.org/packages/58/59/b492a806a899f28609d4333e009e89be8558ca8dd9c61146e5f562e761c2/msmbuilder-3.5.0.tar.gz#md5=0fdf47eac1fd423b3edb1c2a84dfb2e9
    md5: 0fdf47eac1fd423b3edb1c2a84dfb2e9

extra:
  upload: rc

build:
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - mdtraj
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc

test:
  imports:
    - msmbuilder
  commands:
    - msmb -h


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'

# vim: ts=2 sw=2 expandtab
