package:
  name: msmbuilder
  version: !!str 3.3.0

source:
    fn: msmbuilder-3.3.0.tar.gz
    url: https://pypi.python.org/packages/source/m/msmbuilder/msmbuilder-3.3.0.tar.gz#md5=95b458908e53c65e0c0560398a412389
    md5: 95b458908e53c65e0c0560398a412389

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main


requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - mdtraj
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables


test:
  requires:
    - nose
    - munkres
    - numdifftools
  imports:
    - msmbuilder
  commands:
    - msmb -h
    - nosetests msmbuilder -v


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'
