package:
  name: msmbuilder
  version: "3.6.1"

source:
    fn: msmbuilder-3.6.1.tar.gz
    url: https://pypi.python.org/packages/75/c9/806c06d13a032e20d12c6ccbd318de783b18a99e0c49f0c497007ca2f796/msmbuilder-3.6.1.tar.gz#md5=0659b50d7f736dae2547c0ce4e74724d
    md5: 0659b50d7f736dae2547c0ce4e74724d

extra:
  upload: rc

build:
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main
  skip:
    # (2016-06-23) conda build quietly refuses to build this config.
    - [win and np == 111]
    # These configurations don't work and I don't want to figure out why
    - [win64 and py27]
    - [win64 and py34]

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - mdtraj
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc
    - pyyaml
    - jinja2
    - fastcluster

test:
  imports:
    - msmbuilder
  commands:
    - msmb -h


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'

# vim: ts=2 sw=2 expandtab
