package:
  name: sphinxcontrib-autodoc_doxygen
  version: "0.3.1"

source:
  fn: sphinxcontrib-autodoc_doxygen-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-autodoc_doxygen/sphinxcontrib-autodoc_doxygen-0.3.1.tar.gz
  md5: fcfbc77a810900865b143b7aa9409e2f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-autodoc_doxygen = sphinxcontrib-autodoc_doxygen:main
    #
    # Would create an entry point called sphinxcontrib-autodoc_doxygen that calls sphinxcontrib-autodoc_doxygen.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: MIT License
  summary: 'Doxygen / Sphinx bridge, with autodoc and autosummary'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
