package:
  name: sphinxcontrib-autodoc_doxygen
  version: "0.3.1"

source:
  fn: release.zip
  url: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/archive/0.3.1.zip

build:
  noarch_python: True

requirements:
  build:
    - setuptools
    - python
    - sphinx ==1.3.1
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml
    - mock
    - pbr

  run:
    - python
    - sphinx ==1.3.1
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml
    - mock
    - pbr

about:
  home: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen
  license: MIT License
  summary: 'Doxygen / Sphinx bridge, with autodoc and autosummary'
