package:
  name: pdbfixer
  version: 1.4

source:
  fn: 1.4.tar.gz
  url: https://github.com/pandegroup/pdbfixer/archive/1.4.tar.gz

build:
  number: 0
  entry_points:
    - pdbfixer = pdbfixer.pdbfixer:main
  skip: True  # [win32 or (win and py2k)]

requirements:
  build:
    - python
    - setuptools
    - openmm >=7.1.0rc1
    - numpy

  run:
    - python
    - openmm >=7.1.0rc1
    - numpy

test:
  commands:
    - pdbfixer -h
    # - nosetests pdbfixer --nocapture --verbosity=2 --with-doctest
  imports:
    - pdbfixer

about:
  home: http://github.com/simtk/pdbfixer
  license: MIT
  summary: PDBFixer fixes problems in PDB files to prepare them for molecular simulation.
