package:
  name: pdbfixer
  version: 1.6

source:
  git_url: https://github.com/pandegroup/pdbfixer.git
  git_tag: 6343731

build:
  number: 0
  entry_points:
    - pdbfixer = pdbfixer.pdbfixer:main
  skip: True  # [win32 or (win and py2k)]

extra:
  upload: rc
  force_upload: False
  include_omnia_label: rc

requirements:
  build:
    - python
    - setuptools
    - openmm >=7.4.0
    - numpy >=1.14

  run:
    - python
    - openmm >=7.4.0
    - numpy >=1.14

test:
  commands:
    - pdbfixer -h
    # - nosetests pdbfixer --nocapture --verbosity=2 --with-doctest
  imports:
    - pdbfixer

about:
  home: http://github.com/simtk/pdbfixer
  license: MIT
  summary: PDBFixer fixes problems in PDB files to prepare them for molecular simulation.
