package:
  name: fastcluster
  version: !!str 1.1.20

source:
  fn: fastcluster-1.1.20.tar.gz
  url: https://pypi.python.org/packages/source/f/fastcluster/fastcluster-1.1.20.tar.gz
  md5: 4f15531a99ce0f203761b0e31d7ca53c

requirements:
  build:
    - python
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  # Python imports
  imports:
    - fastcluster

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://danifold.net
  license: BSD License or GNU General Public License v2 (GPLv2)
  summary: 'Fast hierarchical clustering routines for R and Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
